---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-pool-manager
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:     ["get", "list", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-pool-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-pool-manager
subjects:
  - kind: ServiceAccount
    name: kube-pool-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: kube-pool-manager
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: kube-pool-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-pool-manager
