---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-bootstrap-token-manager
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-bootstrap-token-manager
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: kube-bootstrap-token-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-bootstrap-token-manager
