apiVersion: v1
kind: Secret
metadata:
  name: kube-bootstrap-token-manager
  namespace: kube-system
type: Opaque
data:
  #####################################
  # CloudProvider: azure
  cloudprovider-azure.json: e30=
#    {
#      "tenantId": "01234abc-de56-ff78-abc1-234567890def",
#      "subscriptionId": "01234abc-de56-ff78-abc1-234567890def",
#      "resourceGroup": "resource-group",
#      "aadClientId": "01234abc-de56-ff78-abc1-234567890def",
#      "aadClientSecret": "uKiuXeiwui4jo9quae9o"
#    }
